
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Loic
 */
public class SimpleCountUI extends javax.swing.JFrame {

    /**
     * Creates new form SimpleCountUI
     */
    private SimpleCount calc = new SimpleCount();
    
    public SimpleCountUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        buttonMC = new javax.swing.JButton();
        buttonMR = new javax.swing.JButton();
        buttonMAdd = new javax.swing.JButton();
        buttonMSubstract = new javax.swing.JButton();
        buttonSquareRoot = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonModulo = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMul = new javax.swing.JButton();
        buttonInverse = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonComa = new javax.swing.JButton();
        buttonSign = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonResult = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonSin = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonSquare = new javax.swing.JButton();
        buttonLog = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimpleCount");
        setResizable(false);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setToolTipText("");
        jTextField1.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        buttonMC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMC.setText("MC");
        buttonMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMCActionPerformed(evt);
            }
        });

        buttonMR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMR.setText("MR");
        buttonMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMRActionPerformed(evt);
            }
        });

        buttonMAdd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMAdd.setText("M+");
        buttonMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMAddActionPerformed(evt);
            }
        });

        buttonMSubstract.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMSubstract.setText("M-");
        buttonMSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMSubstractActionPerformed(evt);
            }
        });

        buttonSquareRoot.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonSquareRoot.setText("\u221A");
        buttonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSquareRootActionPerformed(evt);
            }
        });

        button7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonDivide.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonModulo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonModulo.setText("%");
        buttonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModuloActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        buttonMul.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMul.setText("*");
        buttonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMulActionPerformed(evt);
            }
        });

        buttonInverse.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonInverse.setText("1/x");
        buttonInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInverseActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonMinus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        button0.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonComa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonComa.setText(",");
        buttonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComaActionPerformed(evt);
            }
        });

        buttonSign.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonSign.setText("+/-");
        buttonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonResult.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonResult.setText("=");
        buttonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultActionPerformed(evt);
            }
        });

        buttonC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonMC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buttonMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonMSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(buttonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttonAdd, buttonComa, buttonDivide, buttonInverse, buttonMAdd, buttonMC, buttonMR, buttonMSubstract, buttonMinus, buttonModulo, buttonMul, buttonResult, buttonSign, buttonSquareRoot});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(buttonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonMR)
                        .addComponent(buttonMAdd)
                        .addComponent(buttonMSubstract)
                        .addComponent(buttonSquareRoot)))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button7)
                    .addComponent(button8)
                    .addComponent(button9)
                    .addComponent(buttonDivide)
                    .addComponent(buttonModulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button4)
                    .addComponent(button5)
                    .addComponent(button6)
                    .addComponent(buttonMul)
                    .addComponent(buttonInverse))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button1)
                            .addComponent(button2)
                            .addComponent(button3)
                            .addComponent(buttonMinus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button0)
                            .addComponent(buttonComa)
                            .addComponent(buttonSign)
                            .addComponent(buttonAdd)))
                    .addComponent(buttonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttonAdd, buttonC, buttonComa, buttonDivide, buttonInverse, buttonMAdd, buttonMC, buttonMR, buttonMSubstract, buttonMinus, buttonModulo, buttonMul, buttonSign, buttonSquareRoot});

        buttonSin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonSin.setText("sin");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonTan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonTan.setText("tan");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });

        buttonSquare.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonSquare.setText("x²");
        buttonSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSquareActionPerformed(evt);
            }
        });

        buttonLog.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonLog.setText("log");
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });

        buttonExp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonExp.setText("exp");
        buttonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExpActionPerformed(evt);
            }
        });

        buttonCos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonCos.setText("cos");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCos, buttonExp, buttonLog, buttonSin, buttonSquare, buttonTan});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(buttonCos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(buttonTan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonCos, buttonExp, buttonLog, buttonSin, buttonSquare, buttonTan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("7");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("8");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button8ActionPerformed

    private void buttonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComaActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral(",");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonComaActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("0");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("1");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("2");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("3");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("4");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("5");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("6");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button6ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.addNumeral("9");
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        calc.clearTotally();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignActionPerformed
        if ("+".equals(jTextField1.getText()) || "-".equals(jTextField1.getText()) || "*".equals(jTextField1.getText()) || "/".equals(jTextField1.getText()) || "%".equals(jTextField1.getText()))
            calc.clearBuffer();
        calc.invertSign();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonSignActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        
       if (!"+".equals(jTextField1.getText()) && !"-".equals(jTextField1.getText()) && !"*".equals(jTextField1.getText()) && !"/".equals(jTextField1.getText()) && !"%".equals(jTextField1.getText()))
        {
            if (calc.getOperator() != 0)
                calc.setResult();
            calc.actualToBuffer();
        }
        calc.setOperator(1);
        jTextField1.setText("+");
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed

       if (!"+".equals(jTextField1.getText()) && !"-".equals(jTextField1.getText()) && !"*".equals(jTextField1.getText()) && !"/".equals(jTextField1.getText()) && !"%".equals(jTextField1.getText()))
        {
            if (calc.getOperator() != 0)
                calc.setResult();
            calc.actualToBuffer();
        }
        calc.setOperator(2);
    //    calc.actualToBuffer();
        jTextField1.setText("-");
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMulActionPerformed
        
       if (!"+".equals(jTextField1.getText()) && !"-".equals(jTextField1.getText()) && !"*".equals(jTextField1.getText()) && !"/".equals(jTextField1.getText()) && !"%".equals(jTextField1.getText()))
        {
            if (calc.getOperator() != 0)
                calc.setResult();
            calc.actualToBuffer();
        }
        calc.setOperator(3);
  //      calc.actualToBuffer();
        jTextField1.setText("*");
    }//GEN-LAST:event_buttonMulActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        
        if (!"+".equals(jTextField1.getText()) && !"-".equals(jTextField1.getText()) && !"*".equals(jTextField1.getText()) && !"/".equals(jTextField1.getText()) && !"%".equals(jTextField1.getText()))
        {
            if (calc.getOperator() != 0)
                calc.setResult();
            calc.actualToBuffer();
        }
        calc.setOperator(4);
//        calc.actualToBuffer();
        jTextField1.setText("/");
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModuloActionPerformed
        
        if (!"+".equals(jTextField1.getText()) && !"-".equals(jTextField1.getText()) && !"*".equals(jTextField1.getText()) && !"/".equals(jTextField1.getText()) && !"%".equals(jTextField1.getText()))
        {
            if (calc.getOperator() != 0)
                calc.setResult();
            calc.actualToBuffer();
        }
        calc.setOperator(5);
      //  calc.actualToBuffer();
        jTextField1.setText("%");
    }//GEN-LAST:event_buttonModuloActionPerformed

    private void buttonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultActionPerformed
        calc.setResult();
        jTextField1.setText(calc.getActualBuffer());
        calc.clearAll();
    }//GEN-LAST:event_buttonResultActionPerformed

    private void buttonInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInverseActionPerformed
        calc.inverseNumber();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonInverseActionPerformed

    private void buttonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSquareRootActionPerformed
        calc.squareRootNumber();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonSquareRootActionPerformed

    private void buttonMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMCActionPerformed
        calc.clearMemory();
        jTextField1.setText(calc.getActualBuffer());        
    }//GEN-LAST:event_buttonMCActionPerformed

    private void buttonMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMRActionPerformed
        calc.getMemory();
        jTextField1.setText(calc.getActualBuffer());        
    }//GEN-LAST:event_buttonMRActionPerformed

    private void buttonMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMAddActionPerformed
        calc.addToMemory();
        jTextField1.setText(calc.getActualBuffer());        
    }//GEN-LAST:event_buttonMAddActionPerformed

    private void buttonMSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMSubstractActionPerformed
        calc.subToMemory();
        jTextField1.setText(calc.getActualBuffer());        
    }//GEN-LAST:event_buttonMSubstractActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        calc.tangeante();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        calc.cosinus();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        calc.sinus();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSquareActionPerformed
        calc.square();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonSquareActionPerformed

    private void buttonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogActionPerformed
        calc.logarythm();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonLogActionPerformed

    private void buttonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExpActionPerformed
        calc.exponential();
        jTextField1.setText(calc.getActualBuffer());
    }//GEN-LAST:event_buttonExpActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCountUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonComa;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonInverse;
    private javax.swing.JButton buttonLog;
    private javax.swing.JButton buttonMAdd;
    private javax.swing.JButton buttonMC;
    private javax.swing.JButton buttonMR;
    private javax.swing.JButton buttonMSubstract;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonModulo;
    private javax.swing.JButton buttonMul;
    private javax.swing.JButton buttonResult;
    private javax.swing.JButton buttonSign;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonSquare;
    private javax.swing.JButton buttonSquareRoot;
    private javax.swing.JButton buttonTan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
